"""Pydantic parameter models for all MCP tools.

This module is organized into category submodules:
- core: Fetch, Spider, Markdown, Search, GitHub, etc.
- llm: LLM provider operations (chat, extract, classify, etc.)
- intelligence: Social, threat, metadata, crypto analysis
- adversarial: Adversarial attack and red-team parameters
- infrastructure: Sessions, config, cache, billing, workflows
- academic: Citation analysis, retraction checking, etc.
- security: Security scanning, breach checking, CVE lookup
- research: Comprehensive research and analysis tools

For backward compatibility, all parameter models are re-exported
at the package level, so existing imports like:
    from loom.params import FetchParams
will continue to work.
"""

from __future__ import annotations

# Core research tools
from loom.params.core import (
    BotasaurusParams,
    CamoufoxParams,
    CommitAnalyzerParams,
    ContentAuthenticityParams,
    DeadContentParams,
    DeepfakeCheckerParams,
    DeepParams,
    DetectParadoxParams,
    ExploitSearchParams,
    FetchParams,
    GitHubParams,
    GitHubSearchParams,
    LightpandaFetchParams,
    MarkdownParams,
    MultiSearchParams,
    NodriverFetchParams,
    PDFSearchParams,
    PolyglotSearchParams,
    PropagandaDetectorParams,
    RefusalDetectorParams,
    RegistryGraveyardParams,
    RSSFetchParams,
    RSSSearchParams,
    ScraperEngineFetchParams,
    SearchDiscrepancyParams,
    SearchParams,
    SpiderParams,
    WaybackParams,
    ZenFetchParams,
)

# LLM tools
from loom.params.llm import (
    ArticleExtractParams,
    CamelotTableExtractParams,
    EmbeddingCollideParams,
    ExtractCookiesParams,
    InstructorStructuredExtractParams,
    KnowledgeExtractParams,
    LLMAnswerParams,
    LLMChatParams,
    LLMClassifyParams,
    LLMEmbedParams,
    LLMExtractParams,
    LLMQueryExpandParams,
    LLMSummarizeParams,
    LLMTranslateParams,
    NodriverExtractParams,
    PDFExtractParams,
    ScraperEngineExtractParams,
    StructuredCrawlParams,
    StructuredLLMParams,
    UnstructuredDocumentExtractParams,
)

# Intelligence tools
from loom.params.intelligence import (
    CitationGraphParams,
    CompanyDiligenceParams,
    CompetitiveIntelParams,
    CredentialMonitorParams,
    CryptoRiskParams,
    CryptoTraceParams,
    DeceptionDetectParams,
    DependencyAuditParams,
    EthereumTxDecodeParams,
    FindExpertsParams,
    GraphAnalyzeParams,
    GraphScraperParams,
    LeakScanParams,
    MetadataForensicsParams,
    MultilingualBenchmarkParams,
    MultilingualParams,
    MultiPageGraphParams,
    PatentLandscapeParams,
    RedTeamParams,
    SalaryIntelligenceParams,
    SocialGraphParams,
    SocialProfileParams,
    SocialSearchParams,
    StegoAnalyzeParams,
    StegoDetectParams,
    StegoEncodeParams,
    SupplyChainRiskParams,
    ThreatProfileParams,
    TransactionGraphParams,
)

# Adversarial tools
from loom.params.adversarial import (
    ActiveSelectParams,
    AdversarialBatchParams,
    AdversarialDebateAttackerParams,
    AttackEconomyLeaderboardParams,
    AttackEconomySubmitParams,
    CaptureHarParams,
    CraftAdversarialParams,
    FuseEvidenceParams,
    HITLEvaluateParams,
    HITLQueueParams,
    HITLSubmitParams,
    LifetimeOracleParams,
    ModelEvidenceParams,
    PredictAttacksParams,
    PreemptivePatchParams,
    ResiliencePredictorParams,
    ScapyPacketCraftParams,
    SuperpositionPromptParams,
    SwarmAttackParams,
    UncertaintyEstimateParams,
)

# Infrastructure tools
from loom.params.infrastructure import (
    CacheClearParams,
    CacheStatsParams,
    CachedStrategyParams,
    ConfigGetParams,
    ConfigSetParams,
    EmailReportParams,
    NodriverSessionParams,
    SessionCloseParams,
    SessionOpenParams,
    StripeCancelSubscriptionParams,
    StripeCreateChargeParams,
    StripeCreateCheckoutParams,
    StripeCreateSubscriptionParams,
    StripeGetInvoiceParams,
    StripeListInvoicesParams,
    SuggestWorkflowParams,
    WorkflowCreateParams,
    WorkflowRunParams,
    WorkflowStatusParams,
)

# Academic tools
from loom.params.academic import (
    CitationAnalysisParams,
    OpenAccessParams,
    PredatoryJournalCheckParams,
    RetractionCheckParams,
    SubdomainTemporalParams,
    TemporalAnomalyParams,
    TemporalDiffParams,
)

# Security tools
from loom.params.security import (
    BreachCheckParams,
    CensysHostParams,
    CensysSearchParams,
    CertAnalyzeParams,
    CVEDetailParams,
    CVELookupParams,
    DefiSecurityAuditParams,
    DNSLookupParams,
    ModelIntegrityParams,
    ModelVulnerabilityProfileParams,
    NmapScanParams,
    PackageAuditParams,
    PasswordCheckParams,
    SecurityHeadersParams,
    ShodanHostParams,
    ShodanSearchParams,
    URLhausSearchParams,
    WhoisParams,
)

# Research tools (largest category)
from loom.params.research import (
    AdaptComplexityParams,
    AdaptiveReframeParams,
    AgentBenchmarkParams,
    AggregateResultsParams,
    AggregateTextsParams,
    AmassEnumParams,
    AmassIntelParams,
    ArticleBatchParams,
    ArxivScanParams,
    AttackerTargetDebateParams,
    AuthorityStackParams,
    AutoReframeParams,
    BPJParams,
    BenchmarkParams,
    ChainDefineParams,
    ChainDescribeParams,
    CheckpointListParams,
    CheckpointResumeParams,
    CheckpointSaveParams,
    CicdRunParams,
    CircuitBypassPlanParams,
    ConsensusParams,
    ConsistencyPressureHistoryParams,
    ConsistencyPressureParams,
    ConsistencyPressureRecordParams,
    ContextPoisonParams,
    CoverageRunParams,
    CrawlParams,
    CreepjsParams,
    CrescendoChainParams,
    CrossModelTransferParams,
    DaisyChainParams,
    DarkForumParams,
    DarkWebBridgeParams,
    DashboardParams,
    DataPoisoningParams,
    DocumentAnalyzeParams,
    DriftMonitorParams,
    ExaFindSimilarParams,
    ExecutabilityParams,
    ExperimentDesignParams,
    ExploitRegisterParams,
    ExportCsvParams,
    ExportJsonParams,
    ExportListParams,
    FOIATrackerParams,
    FingerprintBehaviorParams,
    FingerprintEvasionParams,
    FingerprintModelParams,
    FormatSmuggleParams,
    FullSpectrumParams,
    FunctorMapParams,
    GeodesicPathParams,
    GhostProtocolParams,
    GithubReadmeParams,
    GithubReleasesParams,
    HCSReportParams,
    HCSRubricParams,
    HierarchicalResearchParams,
    HttpxProbeParams,
    ImageAnalyzeParams,
    InfluenceOperationParams,
    InfoHalfLifeParams,
    InformationCascadeParams,
    InfraCorrelatorParams,
    InstagramParams,
    InvisibleWebParams,
    JSIntelParams,
    KatanaCrawlParams,
    LegalTakedownParams,
    LightpandaBatchParams,
    MemeticSimulateParams,
    MemoryRecallParams,
    MemoryStoreParams,
    MetaLearnerParams,
    MisinfoCheckParams,
    ModelComparatorParams,
    NucleiScanParams,
    OCRAdvancedParams,
    OnionDiscoverParams,
    OrchestrateSmartParams,
    PDFAdvancedParams,
    PaddleOCRParams,
    ParadoxImmunizeParams,
    ParallelExecutorParams,
    ParallelPlanExecutorParams,
    PersistentMemoryRecallParams,
    PersistentMemoryRememberParams,
    PersonalizeOutputParams,
    PotencyScoreParams,
    PromptReframeParams,
    PydanticAgentParams,
    QueryBuilderParams,
    RAGAttackParams,
    RecommendNextParams,
    RunExperimentParams,
    SafetyCircuitMapParams,
    SaveNoteParams,
    ScraperEngineBatchParams,
    SecTrackerParams,
    SherlockBatchParams,
    SherlockLookupParams,
    SimplifyParams,
    SitemapCrawlParams,
    SourceCredibilityParams,
    StackReframeParams,
    StrangeAttractorParams,
    StylometryParams,
    SubcultureIntelParams,
    SubfinderParams,
    SynthesizeReportParams,
    TaskCriticalPathParams,
    TaskResolveOrderParams,
    TextToSpeechParams,
    ToolRecommendParams,
    TorbotParams,
    ToxicityCheckParams,
    UnifiedScoreParams,
    VisionBrowseParams,
    VisionCompareParams,
    WebTimeMachineParams,
    WhiteRabbitParams,
    WikiEventCorrelatorParams,
    ZenBatchParams,
    ZenInteractParams,
)

__all__ = [
    # Core
    "BotasaurusParams",
    "CamoufoxParams",
    "CommitAnalyzerParams",
    "ContentAuthenticityParams",
    "DeadContentParams",
    "DeepfakeCheckerParams",
    "DeepParams",
    "DetectParadoxParams",
    "ExploitSearchParams",
    "FetchParams",
    "GitHubParams",
    "GitHubSearchParams",
    "LightpandaFetchParams",
    "MarkdownParams",
    "MultiSearchParams",
    "NodriverFetchParams",
    "PDFSearchParams",
    "PolyglotSearchParams",
    "PropagandaDetectorParams",
    "RefusalDetectorParams",
    "RegistryGraveyardParams",
    "RSSFetchParams",
    "RSSSearchParams",
    "ScraperEngineFetchParams",
    "SearchDiscrepancyParams",
    "SearchParams",
    "SpiderParams",
    "WaybackParams",
    "ZenFetchParams",
    # LLM
    "ArticleExtractParams",
    "CamelotTableExtractParams",
    "EmbeddingCollideParams",
    "ExtractCookiesParams",
    "InstructorStructuredExtractParams",
    "KnowledgeExtractParams",
    "LLMAnswerParams",
    "LLMChatParams",
    "LLMClassifyParams",
    "LLMEmbedParams",
    "LLMExtractParams",
    "LLMQueryExpandParams",
    "LLMSummarizeParams",
    "LLMTranslateParams",
    "NodriverExtractParams",
    "PDFExtractParams",
    "ScraperEngineExtractParams",
    "StructuredCrawlParams",
    "StructuredLLMParams",
    "UnstructuredDocumentExtractParams",
    # Intelligence
    "CitationGraphParams",
    "CompanyDiligenceParams",
    "CompetitiveIntelParams",
    "CredentialMonitorParams",
    "CryptoRiskParams",
    "CryptoTraceParams",
    "DeceptionDetectParams",
    "DependencyAuditParams",
    "EthereumTxDecodeParams",
    "FindExpertsParams",
    "GraphAnalyzeParams",
    "GraphScraperParams",
    "LeakScanParams",
    "MetadataForensicsParams",
    "MultilingualBenchmarkParams",
    "MultilingualParams",
    "MultiPageGraphParams",
    "PatentLandscapeParams",
    "RedTeamParams",
    "SalaryIntelligenceParams",
    "SocialGraphParams",
    "SocialProfileParams",
    "SocialSearchParams",
    "StegoAnalyzeParams",
    "StegoDetectParams",
    "StegoEncodeParams",
    "SupplyChainRiskParams",
    "ThreatProfileParams",
    "TransactionGraphParams",
    # Adversarial
    "ActiveSelectParams",
    "AdversarialBatchParams",
    "AdversarialDebateAttackerParams",
    "AttackEconomyLeaderboardParams",
    "AttackEconomySubmitParams",
    "CaptureHarParams",
    "CraftAdversarialParams",
    "FuseEvidenceParams",
    "HITLEvaluateParams",
    "HITLQueueParams",
    "HITLSubmitParams",
    "LifetimeOracleParams",
    "ModelEvidenceParams",
    "PredictAttacksParams",
    "PreemptivePatchParams",
    "ResiliencePredictorParams",
    "ScapyPacketCraftParams",
    "SuperpositionPromptParams",
    "SwarmAttackParams",
    "UncertaintyEstimateParams",
    # Infrastructure
    "CacheClearParams",
    "CacheStatsParams",
    "CachedStrategyParams",
    "ConfigGetParams",
    "ConfigSetParams",
    "EmailReportParams",
    "NodriverSessionParams",
    "SessionCloseParams",
    "SessionOpenParams",
    "StripeCancelSubscriptionParams",
    "StripeCreateChargeParams",
    "StripeCreateCheckoutParams",
    "StripeCreateSubscriptionParams",
    "StripeGetInvoiceParams",
    "StripeListInvoicesParams",
    "SuggestWorkflowParams",
    "WorkflowCreateParams",
    "WorkflowRunParams",
    "WorkflowStatusParams",
    # Academic
    "CitationAnalysisParams",
    "OpenAccessParams",
    "PredatoryJournalCheckParams",
    "RetractionCheckParams",
    "SubdomainTemporalParams",
    "TemporalAnomalyParams",
    "TemporalDiffParams",
    # Security
    "BreachCheckParams",
    "CensysHostParams",
    "CensysSearchParams",
    "CertAnalyzeParams",
    "CVEDetailParams",
    "CVELookupParams",
    "DefiSecurityAuditParams",
    "DNSLookupParams",
    "ModelIntegrityParams",
    "ModelVulnerabilityProfileParams",
    "NmapScanParams",
    "PackageAuditParams",
    "PasswordCheckParams",
    "SecurityHeadersParams",
    "ShodanHostParams",
    "ShodanSearchParams",
    "URLhausSearchParams",
    "WhoisParams",
]
